-- TEMPORARY RLS DISABLE FOR DEVELOPMENT
-- This disables RLS to allow immediate functionality
-- Re-enable with proper policies in production

ALTER TABLE public.assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaigns DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.stream_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.placements DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.murals DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cards DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.mural_cards DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.decks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.deck_assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.processing_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.asset_streams DISABLE ROW LEVEL SECURITY;